#!/usr/bin/env node
var homa = require('homa');
var systemId = homa.paramsWithDefaultSystemId("391349-logger");

homa.mqttHelper.on('connect', function(packet) {
	console.log(systemId)
	homa.mqttHelper.subscribe('#');
});

homa.mqttHelper.on('message', function(packet) {
	console.log("%s topic: %s, payload: %s, qos: %s, messageId: %s, retained: %s", new Date(), packet.topic, packet.payload, packet.qos, packet.mid, packet.retain);
});

(function connect() {
	homa.mqttHelper.connect();
})();


